# To modify the layout, see https://jekyllrb.com/docs/themes/#overriding-theme-defaults

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings. Accessd via {{ site.<key> }}.
title: Reflekt
email: maediprichard@gmail.com
description: Reflective testing.
baseurl: ""
url: "https://reflekt.dev"
twitter_username: maediprichard
github_username:  refIekt

# Build settings.
markdown: kramdown
theme: bulma-clean-theme
plugins:
  - jekyll-feed

# Theme.
layout: page
defaults:
  -
    scope:
      type: pages
    values:
      show_hero: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
